// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pricing.Infrastructure.Persistence;

#nullable disable

namespace Pricing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20260421100029_InitialPricingSchema")]
    partial class InitialPricingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pricing.Domain.Entities.PriceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId", "IsActive");

                    b.ToTable("PriceEntries", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.Entities.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "Status");

                    b.HasIndex("StoreId", "Currency", "Priority");

                    b.HasIndex("StoreId", "Currency", "IsDefault", "Status");

                    b.ToTable("PriceLists", (string)null);
                });

            modelBuilder.Entity("Pricing.Domain.Entities.PriceEntry", b =>
                {
                    b.HasOne("Pricing.Domain.Entities.PriceList", null)
                        .WithMany("Entries")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pricing.Domain.ValueObjects.Money", "CompareAtPrice", b1 =>
                        {
                            b1.Property<Guid>("PriceEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CompareAtAmount");

                            b1.HasKey("PriceEntryId");

                            b1.ToTable("PriceEntries");

                            b1.WithOwner()
                                .HasForeignKey("PriceEntryId");

                            b1.OwnsOne("Pricing.Domain.ValueObjects.Currency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("MoneyPriceEntryId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("CompareAtCurrencyCode");

                                    b2.HasKey("MoneyPriceEntryId");

                                    b2.ToTable("PriceEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyPriceEntryId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("Pricing.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("PriceEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("PriceEntryId");

                            b1.ToTable("PriceEntries");

                            b1.WithOwner()
                                .HasForeignKey("PriceEntryId");

                            b1.OwnsOne("Pricing.Domain.ValueObjects.Currency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("MoneyPriceEntryId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("CurrencyCode");

                                    b2.HasKey("MoneyPriceEntryId");

                                    b2.ToTable("PriceEntries");

                                    b2.WithOwner()
                                        .HasForeignKey("MoneyPriceEntryId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("Pricing.Domain.ValueObjects.PriceTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("PriceEntryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProductId");

                            b1.Property<Guid?>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProductVariantId");

                            b1.HasKey("PriceEntryId");

                            b1.ToTable("PriceEntries");

                            b1.WithOwner()
                                .HasForeignKey("PriceEntryId");
                        });

                    b.Navigation("CompareAtPrice");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Pricing.Domain.Entities.PriceList", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
